# Generated by Django 5.2.1 on 2025-05-30 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=20, verbose_name='路线编号')),
                ('name', models.CharField(max_length=100, verbose_name='路线名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('frequency', models.CharField(max_length=50, verbose_name='发车频率')),
                ('operating_cars', models.CharField(max_length=20, verbose_name='运营车辆')),
            ],
            options={
                'verbose_name': '路线',
                'verbose_name_plural': '路线',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='交通类型名称')),
                ('icon', models.CharField(max_length=255, verbose_name='图标路径')),
            ],
            options={
                'verbose_name': '交通类型',
                'verbose_name_plural': '交通类型',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(verbose_name='到达时间')),
                ('day_of_week', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期几')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.route', verbose_name='路线')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.stop', verbose_name='站点')),
            ],
            options={
                'verbose_name': '时刻表',
                'verbose_name_plural': '时刻表',
                'ordering': ['day_of_week', 'arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('good', '良好'), ('warning', '轻微延迟'), ('bad', '严重延迟')], default='good', max_length=20, verbose_name='状态')),
                ('details', models.TextField(verbose_name='详情')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.transporttype', verbose_name='交通类型')),
            ],
            options={
                'verbose_name': '系统状态',
                'verbose_name_plural': '系统状态',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.transporttype', verbose_name='交通类型'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.route', verbose_name='相关路线')),
                ('transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.transporttype', verbose_name='相关交通类型')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='路线别名')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_routes', to='api.stop', verbose_name='起始站点')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.route', verbose_name='路线')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_routes', to='api.stop', verbose_name='终点站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户路线',
                'verbose_name_plural': '用户路线',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='启用提醒')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='启用通知')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='站点顺序')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.route', verbose_name='路线')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.stop', verbose_name='站点')),
            ],
            options={
                'verbose_name': '路线站点',
                'verbose_name_plural': '路线站点',
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
