# Generated by Django 5.2.1 on 2025-05-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userroute_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='站点顺序')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.route', verbose_name='路线')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.stop', verbose_name='站点')),
            ],
            options={
                'verbose_name': '路线站点',
                'verbose_name_plural': '路线站点',
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ] 