# Generated by Django 5.2.1 on 2025-06-13 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_routestop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='API名称')),
                ('key', models.CharField(max_length=255, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('allowed_ips', models.TextField(blank=True, verbose_name='允许的IP地址列表(逗号分隔)')),
                ('rate_limit', models.IntegerField(default=100, verbose_name='每小时请求限制')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='提醒标题')),
                ('description', models.TextField(blank=True, verbose_name='提醒内容')),
                ('reminder_time', models.DateTimeField(verbose_name='提醒时间')),
                ('advance_notice', models.IntegerField(default=15, verbose_name='提前通知时间(分钟)')),
                ('repeat_type', models.CharField(choices=[('once', '一次性'), ('daily', '每天'), ('weekdays', '工作日'), ('weekends', '周末'), ('weekly', '每周'), ('monthly', '每月')], default='once', max_length=20, verbose_name='重复类型')),
                ('repeat_days', models.CharField(blank=True, max_length=50, verbose_name='重复日期(如对于weekly, 1,3,5表示周一、三、五)')),
                ('status', models.CharField(choices=[('active', '激活'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_reminders', to='api.stop', verbose_name='起始站点')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='api.route', verbose_name='关联路线')),
                ('to_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_reminders', to='api.stop', verbose_name='目的地站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提醒',
                'verbose_name_plural': '提醒',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='RouteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_load', models.IntegerField(default=0, verbose_name='当前负载百分比')),
                ('delay_minutes', models.IntegerField(default=0, verbose_name='延迟时间(分钟)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('operating_status', models.CharField(choices=[('normal', '正常运行'), ('delayed', '延迟'), ('suspended', '暂停服务'), ('cancelled', '取消服务')], default='normal', max_length=20, verbose_name='运营状态')),
                ('message', models.TextField(blank=True, verbose_name='状态消息')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='api.route', verbose_name='路线')),
            ],
            options={
                'verbose_name': '路线状态',
                'verbose_name_plural': '路线状态',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, verbose_name='车辆ID')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('heading', models.FloatField(default=0, verbose_name='方向角度')),
                ('speed', models.FloatField(default=0, verbose_name='速度(km/h)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='预计到达时间')),
                ('next_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approaching_vehicles', to='api.stop', verbose_name='下一站')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.route', verbose_name='路线')),
            ],
            options={
                'verbose_name': '车辆位置',
                'verbose_name_plural': '车辆位置',
                'ordering': ['-last_updated'],
            },
        ),
    ]
